apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/thienlh/hungthien9394:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/thienlh/hungthien9394:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: hungthien9394
        chartPath: charts/hungthien9394
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/thienlh/hungthien9394"
          image.tag: "{{.TAG}}"
